"""Remove unique constraint on daily_timesheet_entry

Revision ID: 1ffb469bdac6
Revises: 
Create Date: 2025-10-11 11:19:08.078596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffb469bdac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_timesheet_entry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_daily_timesheet_entry'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_timesheet_entry', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_daily_timesheet_entry'), ['consultant_id', 'work_date'])

    # ### end Alembic commands ###
